server:
  port: 8082

spring:
  datasource:
    url: jdbc:mysql://47.104.10.113:3306/renren_security
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver

  mybatis:
    mapper-locations: classpath:mapping/*.xml  #注意：一定要对应mapper映射xml文件的所在路径
    type-aliases-package: com.zhangran.photo_show.model  # 注意：对应实体类的路径

